name: Go CI -- build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: |
          go version

      - name: Run build
        run: go build ./cmd/main.go

      - name: Run vet & lint
        run: |
          go vet ./cmd/main.go

      - name: Run Tests
        run: go test ./test/...
